#!/bin/bash

# qsub -l h_vmem=5G -pe threads 1 -p -19 -q Default.q -o /home/i3scke/MSBlast/Error/Statistics.o -e /home/i3scke/MSBlast/Error/Statistics.e /home/i3scke/MSBlast/callMSBlastStatistics.sh -base /home/i3scke/MSBlast/ -addFolder RPP -ppm 10 -ae 2 -queries QPFilesOriginal-GPFiles,QPFilesOriginal-GPTrees,QPTreesOriginal-GPTrees,OPFilesOriginal-GPFiles,OPFilesOriginal-GPTrees,OPTreesOriginal-GPTrees,BPFilesOriginal-GPFiles,BPFilesOriginal-GPTrees,BPTreesOriginal-GPTrees,GPFilesOriginal-BPFiles,GPFilesOriginal-BPTrees,GPTreesOriginal-BPTrees -searchMethodsStatisticsOriginal CosineDistance,MassBank,OberacherWithIntensities,OberacherWithIntensitiesAndMasses,TreeAlignment -searchMethods CosineDistance,MassBank,OberacherWithIntensities,OberacherWithIntensitiesAndMasses,TreeAlignment -decoyMethods Original,RandomPeaks,MixedSpectrum,ConditionalFast,Reroot,RandomTree -getHitLists -statisticsOriginal -getRankStatistic -checkEquality -getQValues -getQValuesAverage -getQValueSummary -getQValueSummaryPerQValue -getQValueSummaryPerQValueEstimated -getQValueSummaryPerPosition

#qsub -l h_vmem=5G -pe threads 1 -p -19 -q Default.q -o /home/i3scke/MSBlast/Error/Statistics.o -e /home/i3scke/MSBlast/Error/Statistics.e /home/i3scke/MSBlast/callMSBlastStatistics.sh -base /home/i3scke/MSBlast/ -addFolder RPP -ppm 10 -ae 2 -queries APFilesOriginal-GPFiles,APFilesOriginal-GPTrees,APTreesOriginal-GPTrees,OPFilesOriginal-GPFiles,OPFilesOriginal-GPTrees,OPTreesOriginal-GPTrees -searchMethodsStatisticsOriginal CosineDistance,MassBank,OberacherWithIntensities,OberacherWithIntensitiesAndMasses,TreeAlignment -searchMethods CosineDistance,MassBank,OberacherWithIntensities,OberacherWithIntensitiesAndMasses,TreeAlignment -decoyMethods Original,RandomPeaks,MixedSpectrum,ConditionalFast,Reroot,RandomTree -getHitLists -statisticsOriginal -getRankStatistic -checkEquality -getQValues -getQValuesAverage -getQValueSummary

#qsub -l h_vmem=5G -pe threads 1 -p -19 -q Default.q -o /home/i3scke/MSBlast/Error/Statistics.o -e /home/i3scke/MSBlast/Error/Statistics.e /home/i3scke/MSBlast/callMSBlastStatistics.sh -base /home/i3scke/MSBlast/ -addFolder RPP -ppm 10 -ae 2 -queries APFilesOriginal-GPFiles,APFilesOriginal-GPTrees,APTreesOriginal-GPTrees,OPFilesOriginal-GPFiles,OPFilesOriginal-GPTrees,OPTreesOriginal-GPTrees -searchMethodsStatisticsOriginal CosineDistance,MassBank,OberacherWithIntensities,OberacherWithIntensitiesAndMasses,TreeAlignment -searchMethods CosineDistance,MassBank,OberacherWithIntensities,OberacherWithIntensitiesAndMasses,TreeAlignment -decoyMethods Original,RandomPeaks,MixedSpectrum,ConditionalFast,Reroot,RandomTree -getHitLists -getQValues -getQValuesAverage -getQValueSummary

qsub -l h_vmem=5G -pe threads 1 -p -19 -q Default.q -o /home/i3scke/MSBlast/Error/Statistics.o -e /home/i3scke/MSBlast/Error/Statistics.e /home/i3scke/MSBlast/callMSBlastStatistics.sh -base /home/i3scke/MSBlast/ -addFolder RPP -ppm 10 -ae 2 -queries APFilesOriginal-GPFiles,APFilesOriginal-GPTrees,APTreesOriginal-GPTrees,OPFilesOriginal-GPFiles,OPFilesOriginal-GPTrees,OPTreesOriginal-GPTrees -searchMethodsStatisticsOriginal CosineDistance,MassBank,OberacherWithIntensities,OberacherWithIntensitiesAndMasses,TreeAlignment -searchMethods CosineDistance,MassBank,OberacherWithIntensities,OberacherWithIntensitiesAndMasses,TreeAlignment -decoyMethods Original,RandomPeaks,MixedSpectrum,ConditionalFast,Reroot,RandomTree -getHitLists -statisticsOriginal -getRankStatistic -getQValues -getQValuesAverage -getQValueSummary

#qsub -l h_vmem=5G -pe threads 1 -p -19 -q Default.q -o /home/i3scke/MSBlast/Error/Statistics.o -e /home/i3scke/MSBlast/Error/Statistics.e /home/i3scke/MSBlast/callMSBlastStatistics.sh -base /home/i3scke/MSBlast/ -addFolder RPP -ppm 10 -ae 2 -queries APFilesOriginal-GPFiles,APFilesOriginal-GPTrees,APTreesOriginal-GPTrees,OPFilesOriginal-GPFiles,OPFilesOriginal-GPTrees,OPTreesOriginal-GPTrees -searchMethodsStatisticsOriginal CosineDistance,MassBank,OberacherWithIntensities,OberacherWithIntensitiesAndMasses,TreeAlignment -searchMethods CosineDistance,MassBank,OberacherWithIntensities,OberacherWithIntensitiesAndMasses,TreeAlignment -decoyMethods Original,RandomPeaks,MixedSpectrum,ConditionalFast,Reroot,RandomTree -statisticsOriginal